name = "ObaASTs"
uuid = "1070a898-5650-4dbc-bdc4-2f105286d314"
authors = ["josePereiro <jose.pereiro.personal@gmail.com> and contributors"]
version = "0.1.0"

[deps]
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
